/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author esmer
 */
public class Estoque extends javax.swing.JFrame {

    public static int Estoque_update = 0;
    String user;
    DefaultTableModel model = new DefaultTableModel();
    TableRowSorter trs1;

    /**
     * Creates new form Estoque
     */
    public Estoque() {
        initComponents();
        user = Login.user;
        setTitle("Estoque - Sesión de " + user);
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_estoque, tipo_producto, producto, precio_producto, DATE_FORMAT(vencimiento, '%d-%m-%Y') from estoque");
            ResultSet rs = pst.executeQuery();

            jTable_estoque = new JTable(model);
            jScrollPane_estoque.setViewportView(jTable_estoque);

            model.addColumn("ID estoque");
            model.addColumn("Tipo de producto");
            model.addColumn("Producto");
            model.addColumn("Precio");
            model.addColumn("Fecha de vencimiento");

            while (rs.next()) {
                Object[] fila = new Object[5];

                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
            trs1 = new TableRowSorter(model);
            jTable_estoque.setRowSorter(trs1);
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla de estoque");
        }

        TableColumnModel columnModel = jTable_estoque.getColumnModel();
        columnModel.getColumn(0).setMaxWidth(100);
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setMaxWidth(300);
        columnModel.getColumn(1).setPreferredWidth(200);
        columnModel.getColumn(2).setPreferredWidth(500);
        columnModel.getColumn(3).setPreferredWidth(100);
        columnModel.getColumn(3).setMaxWidth(200);
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTable_estoque.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        jTable_estoque.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);

        jTable_estoque.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Estoque_update = (int) jTable_estoque.getValueAt(jTable_estoque.getSelectedRow(), 0);

                if (Estoque_update > 0) {
                    ActualizarEstoque actualizarEstoque = new ActualizarEstoque();
                    actualizarEstoque.setVisible(true);
                    dispose();
                }
            }
        });

        int contar = (jTable_estoque.getRowCount());
        String contarstr = String.valueOf(contar);
        txt_totalproductos.setText(contarstr);

        float sumaCompra = 0;
        for (int i = 0; i < contar; i++) {
            sumaCompra = sumaCompra + Float.parseFloat(jTable_estoque.getValueAt(i, 3).toString());
        }
        String preciostr = String.valueOf(sumaCompra);
        txt_totalprecio.setText(preciostr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_estoque = new javax.swing.JScrollPane();
        jTable_estoque = new javax.swing.JTable();
        jLabel_Nombre14 = new javax.swing.JLabel();
        txt_filtro = new javax.swing.JTextField();
        jLabel_Footer = new javax.swing.JLabel();
        jLabel_Nombre15 = new javax.swing.JLabel();
        cmb_tipoProducto = new javax.swing.JComboBox<>();
        txt_totalproductos = new javax.swing.JTextField();
        txt_totalprecio = new javax.swing.JTextField();
        jLabel_Nombre16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 218, 225));

        jTable_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_estoque.setViewportView(jTable_estoque);
        if (jTable_estoque.getColumnModel().getColumnCount() > 0) {
            jTable_estoque.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable_estoque.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable_estoque.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable_estoque.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jLabel_Nombre14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre14.setText("Filtrar:");

        txt_filtro.setBackground(new java.awt.Color(153, 153, 255));
        txt_filtro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_filtro.setForeground(new java.awt.Color(255, 255, 255));
        txt_filtro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_filtro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtroKeyTyped(evt);
            }
        });

        jLabel_Footer.setText("Creado por Vandreh Esmeraldo ®");

        jLabel_Nombre15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre15.setText("Total de productos: ");

        cmb_tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cuidado de la piel", "Maquillajes", "Fragrancias", "accesorios", "Muestras" }));
        cmb_tipoProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tipoProductoItemStateChanged(evt);
            }
        });

        txt_totalproductos.setBackground(new java.awt.Color(153, 153, 255));
        txt_totalproductos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_totalproductos.setForeground(new java.awt.Color(255, 255, 255));
        txt_totalproductos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_totalproductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_totalprecio.setBackground(new java.awt.Color(153, 153, 255));
        txt_totalprecio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_totalprecio.setForeground(new java.awt.Color(255, 255, 255));
        txt_totalprecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_totalprecio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre16.setText("Total de Precios: $  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_estoque, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nombre14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_tipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Nombre15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_totalproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Nombre16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_totalprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_totalprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_totalproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Nombre16)
                                .addComponent(jLabel_Nombre15))
                            .addGap(27, 27, 27))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_Nombre14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
TableRowSorter trs = null;
    private void txt_filtroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyTyped

        txt_filtro.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent ke) {
                trs1.setRowFilter(RowFilter.regexFilter("(?i)" + txt_filtro.getText(), 2));
            }
        });

        trs1 = new TableRowSorter(model);
        jTable_estoque.setRowSorter(trs1);

    }//GEN-LAST:event_txt_filtroKeyTyped

    private void cmb_tipoProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tipoProductoItemStateChanged
        String query = cmb_tipoProducto.getSelectedItem().toString();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable_estoque.setRowSorter(tr);

        if (query != " ") {
            tr.setRowFilter(RowFilter.regexFilter(query));

        } else {
            jTable_estoque.setRowSorter(tr);
        }
        int contar = (jTable_estoque.getRowCount());
        String contarstr = String.valueOf(contar);
        txt_totalproductos.setText(contarstr);

        float sumaCompra = 0;
        for (int i = 0; i < contar; i++) {
            sumaCompra = sumaCompra + Float.parseFloat(jTable_estoque.getValueAt(i, 3).toString());
        }
        String preciostr = String.valueOf(sumaCompra);
        txt_totalprecio.setText(preciostr);

    }//GEN-LAST:event_cmb_tipoProductoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Estoque().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_tipoProducto;
    private javax.swing.JLabel jLabel_Footer;
    private javax.swing.JLabel jLabel_Nombre14;
    private javax.swing.JLabel jLabel_Nombre15;
    private javax.swing.JLabel jLabel_Nombre16;
    private javax.swing.JScrollPane jScrollPane_estoque;
    private javax.swing.JTable jTable_estoque;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JTextField txt_totalprecio;
    private javax.swing.JTextField txt_totalproductos;
    // End of variables declaration//GEN-END:variables
}
