/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author esmer
 */
public class RegistroFinanciero extends javax.swing.JFrame {

    String user;
    DefaultTableModel compra = new DefaultTableModel();
    DefaultTableModel venta = new DefaultTableModel();
    DefaultTableModel mesCompras = new DefaultTableModel();
    DefaultTableModel mesVentas = new DefaultTableModel();
    DefaultTableModel muestras = new DefaultTableModel();

    /**
     * Creates new form RegistroFinanciero
     */
    public RegistroFinanciero() {
        initComponents();
        user = Login.user;
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Registro financiero - Sesión de: " + user);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jTable_mesCompras = new JTable(mesCompras);
        jScrollPane_mesCompras.setViewportView(jTable_mesCompras);

        mesCompras.addColumn("ID Compra:");
        mesCompras.addColumn("Precio Compra $:");
        mesCompras.addColumn("Flete $:");

        jTable_mesVentas = new JTable(mesVentas);
        jScrollPane_mesVentas.setViewportView(jTable_mesVentas);

        mesVentas.addColumn("ID Venta:");
        mesVentas.addColumn("Cliente Venta:");
        mesVentas.addColumn("Delivery:");
        mesVentas.addColumn("Precio Compra $:");
        mesVentas.addColumn("Valor Venta $:");

        jTable_compras = new JTable(compra);
        jScrollPane_compras.setViewportView(jTable_compras);

        compra.addColumn("ID Compra:");
        compra.addColumn("Fecha Compra:");
        compra.addColumn("Fecha Recepcion:");
        compra.addColumn("Descuento:");
        compra.addColumn("Precio Compra:");
        compra.addColumn("Flete:");

        jTable_ventas = new JTable(venta);
        jScrollPane_ventas.setViewportView(jTable_ventas);

        venta.addColumn("ID Venta:");
        venta.addColumn("Cliente:");
        venta.addColumn("Producto:");
        venta.addColumn("Descuento:");
        venta.addColumn("Delivery:");
        venta.addColumn("Fecha Entrega:");
        venta.addColumn("Precio Venta:");
        venta.addColumn("Fecha Venta:");

        jTable_muestras = new JTable(muestras);
        jScrollPane_muestras.setViewportView(jTable_muestras);

        muestras.addColumn("Id Compra:");
        muestras.addColumn("Tipo Producto:");
        muestras.addColumn("Producto:");
        muestras.addColumn("Precio Producto:");
        muestras.addColumn("Vencimiento:");        

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_compra, DATE_FORMAT(fecha_compra, '%d-%m-%Y'), DATE_FORMAT(fecha_recepcion, '%d-%m-%Y'), descuento_compra, precio_compra, flete from compra");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[6];

                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                compra.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla de compras");
        }

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_venta, cliente_venta, producto_venta, descuento_venta, delivery, DATE_FORMAT(fecha_entrega, '%d-%m-%Y'), precio_venta, DATE_FORMAT(fecha_venta, '%d-%m-%Y') from venta");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[8];

                for (int i = 0; i < 8; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                venta.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla de ventas");
        }
        txt_compras2.setText(Float.toString(totalCompra()));
        txt_ventas2.setText(Float.toString(totalVenta()));
        txt_Lucro2.setText(Float.toString(totalLucro()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel_footer = new javax.swing.JLabel();
        jMonthChooser = new com.toedter.calendar.JMonthChooser();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        jLabel_Titulo = new javax.swing.JLabel();
        jButton_Registrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Nombre5 = new javax.swing.JLabel();
        txt_ventas = new javax.swing.JTextField();
        jLabel_Nombre6 = new javax.swing.JLabel();
        txt_compras = new javax.swing.JTextField();
        jLabel_Nombre7 = new javax.swing.JLabel();
        txt_delivery = new javax.swing.JTextField();
        jLabel_Nombre10 = new javax.swing.JLabel();
        txt_muestras = new javax.swing.JTextField();
        jLabel_Nombre4 = new javax.swing.JLabel();
        txt_Lucro = new javax.swing.JTextField();
        jLabel_DelMes = new javax.swing.JLabel();
        jLabel_Nombre9 = new javax.swing.JLabel();
        jScrollPane_mesCompras = new javax.swing.JScrollPane();
        jTable_mesCompras = new javax.swing.JTable();
        jLabel_Nombre8 = new javax.swing.JLabel();
        jScrollPane_mesVentas = new javax.swing.JScrollPane();
        jTable_mesVentas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Nombre11 = new javax.swing.JLabel();
        jScrollPane_compras = new javax.swing.JScrollPane();
        jTable_compras = new javax.swing.JTable();
        jLabel_DelMes2 = new javax.swing.JLabel();
        jLabel_Nombre20 = new javax.swing.JLabel();
        txt_compras2 = new javax.swing.JTextField();
        jLabel_Nombre19 = new javax.swing.JLabel();
        txt_ventas2 = new javax.swing.JTextField();
        jLabel_Nombre23 = new javax.swing.JLabel();
        txt_Lucro2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Nombre12 = new javax.swing.JLabel();
        jScrollPane_ventas = new javax.swing.JScrollPane();
        jTable_ventas = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane_muestras = new javax.swing.JScrollPane();
        jTable_muestras = new javax.swing.JTable();
        jLabel_Nombre13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 218, 225));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel_footer.setText("Creado por Vandreh Esmeraldo ®");

        jLabel_Titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Titulo.setText("Registro financiero");

        jButton_Registrar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Registrar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Registrar.setText("Registro financiero");
        jButton_Registrar.setBorder(null);
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel_Nombre5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre5.setText("MES VENTAS: $");

        txt_ventas.setBackground(new java.awt.Color(153, 153, 255));
        txt_ventas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ventas.setForeground(new java.awt.Color(255, 255, 255));
        txt_ventas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ventas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre6.setText("MES COMPRAS: $");

        txt_compras.setBackground(new java.awt.Color(153, 153, 255));
        txt_compras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_compras.setForeground(new java.awt.Color(255, 255, 255));
        txt_compras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_compras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre7.setText("TOTAL DELIVERY: $");

        txt_delivery.setBackground(new java.awt.Color(153, 153, 255));
        txt_delivery.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_delivery.setForeground(new java.awt.Color(255, 255, 255));
        txt_delivery.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_delivery.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre10.setText("COSTO DE MUESTRAS: $");

        txt_muestras.setBackground(new java.awt.Color(153, 153, 255));
        txt_muestras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_muestras.setForeground(new java.awt.Color(255, 255, 255));
        txt_muestras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_muestras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre4.setText("LUCRO DEL MES: $");

        txt_Lucro.setBackground(new java.awt.Color(153, 153, 255));
        txt_Lucro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Lucro.setForeground(new java.awt.Color(255, 255, 255));
        txt_Lucro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Lucro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_DelMes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_DelMes.setText("MENSAL:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_DelMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(386, 386, 386))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Nombre5)
                                    .addComponent(txt_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Nombre6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)))
                                .addGap(146, 146, 146)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Nombre4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Lucro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Nombre10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_muestras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Nombre7))))
                        .addContainerGap(121, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_DelMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txt_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Nombre5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Lucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_muestras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel_Nombre9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre9.setText("Compras del mes:");

        jTable_mesCompras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable_mesCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_mesCompras.setViewportView(jTable_mesCompras);

        jLabel_Nombre8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre8.setText("Ventas del mes:");

        jTable_mesVentas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable_mesVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_mesVentas.setViewportView(jTable_mesVentas);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Titulo)
                    .addComponent(jButton_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Nombre9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_footer)
                .addGap(103, 103, 103))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_mesCompras)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre8)
                        .addContainerGap(994, Short.MAX_VALUE))
                    .addComponent(jScrollPane_mesVentas)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMonthChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jYearChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel_Nombre9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_mesCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Nombre8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_mesVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_footer)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("REGISTRO FINANCIERO", jPanel13);

        jLabel_Nombre11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre11.setText("Total de compras:");

        jTable_compras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_compras.setViewportView(jTable_compras);

        jLabel_DelMes2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_DelMes2.setText("TOTAL:");

        jLabel_Nombre20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre20.setText("COMPRAS: $");

        txt_compras2.setBackground(new java.awt.Color(153, 153, 255));
        txt_compras2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_compras2.setForeground(new java.awt.Color(255, 255, 255));
        txt_compras2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_compras2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre19.setText("VENTAS: $");

        txt_ventas2.setBackground(new java.awt.Color(153, 153, 255));
        txt_ventas2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ventas2.setForeground(new java.awt.Color(255, 255, 255));
        txt_ventas2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ventas2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre23.setText("LUCRO TOTAL: $");

        txt_Lucro2.setBackground(new java.awt.Color(153, 153, 255));
        txt_Lucro2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_Lucro2.setForeground(new java.awt.Color(255, 255, 255));
        txt_Lucro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Lucro2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DelMes2)
                            .addComponent(jLabel_Nombre11, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nombre19)
                            .addComponent(txt_ventas2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_compras2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel_Nombre20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(187, 187, 187)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Nombre23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Lucro2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel_DelMes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_compras2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_Nombre23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Lucro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Nombre20)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ventas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113)
                .addComponent(jLabel_Nombre11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TOTAL COMPRAS", jPanel3);

        jLabel_Nombre12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre12.setText("Total de ventas:");

        jTable_ventas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_ventas.setViewportView(jTable_ventas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Nombre12)
                    .addComponent(jScrollPane_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel_Nombre12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TOTAL VENTAS", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1161, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("REGISTRO FINANCIERO TOTAL", jPanel6);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1161, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MES COMPRAS", jPanel12);

        jTable_muestras.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable_muestras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_muestras.setViewportView(jTable_muestras);

        jLabel_Nombre13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_Nombre13.setText("Costo de muestras:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel_Nombre13)
                .addContainerGap(774, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(jScrollPane_muestras)
                    .addGap(213, 213, 213)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel_Nombre13)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addGap(317, 317, 317)
                    .addComponent(jScrollPane_muestras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("MUESTRAS", jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed

        txt_compras.setText("");
        txt_ventas.setText("");
        txt_delivery.setText("");

        mesCompras.getDataVector().removeAllElements();
        jTable_mesCompras.updateUI();
        mesVentas.getDataVector().removeAllElements();
        jTable_mesVentas.updateUI();
        muestras.getDataVector().removeAllElements();
        jTable_muestras.updateUI();

        int mes, ano;
        mes = jMonthChooser.getMonth() + 1;
        ano = jYearChooser.getYear();

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select id_compra, precio_compra, flete from compra where MONTH(fecha_compra) = '" + mes + "' AND YEAR(fecha_compra) = '" + ano + "'");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[3];
                for (int i = 0; i < 3; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                mesCompras.addRow(fila);
            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla mes_compras.");
        }

        txt_compras.setText(Float.toString(sumaMesCompra()));

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select id_venta, cliente_venta, delivery, precio_compra, precio_venta from venta where MONTH(fecha_venta) = '" + mes + "' AND YEAR(fecha_venta) = '" + ano + "'");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                mesVentas.addRow(fila);
            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla mes_ventas.");
        }

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select id_compra, tipo_producto, producto, precio_producto, DATE_FORMAT(vencimiento, '%d-%m-%Y') from productos_comprados where tipo_producto = 'Muestras' AND MONTH(fecha_compra) = '" + mes + "' AND YEAR(fecha_compra) = '" + ano + "'");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[5];

                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                muestras.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla de muestras");
        }

        txt_ventas.setText("");
        txt_delivery.setText("");
        txt_muestras.setText("");
        txt_Lucro.setText("");
        txt_ventas.setText(Float.toString(sumaVenta()));
        txt_delivery.setText(Float.toString(Delivery()));
        txt_muestras.setText(Float.toString(Muestras()));
        txt_Lucro.setText(Float.toString(Lucro()));

    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistroFinanciero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JLabel jLabel_DelMes;
    private javax.swing.JLabel jLabel_DelMes2;
    private javax.swing.JLabel jLabel_Nombre10;
    private javax.swing.JLabel jLabel_Nombre11;
    private javax.swing.JLabel jLabel_Nombre12;
    private javax.swing.JLabel jLabel_Nombre13;
    private javax.swing.JLabel jLabel_Nombre19;
    private javax.swing.JLabel jLabel_Nombre20;
    private javax.swing.JLabel jLabel_Nombre23;
    private javax.swing.JLabel jLabel_Nombre4;
    private javax.swing.JLabel jLabel_Nombre5;
    private javax.swing.JLabel jLabel_Nombre6;
    private javax.swing.JLabel jLabel_Nombre7;
    private javax.swing.JLabel jLabel_Nombre8;
    private javax.swing.JLabel jLabel_Nombre9;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_footer;
    private com.toedter.calendar.JMonthChooser jMonthChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane_compras;
    private javax.swing.JScrollPane jScrollPane_mesCompras;
    private javax.swing.JScrollPane jScrollPane_mesVentas;
    private javax.swing.JScrollPane jScrollPane_muestras;
    private javax.swing.JScrollPane jScrollPane_ventas;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_compras;
    private javax.swing.JTable jTable_mesCompras;
    private javax.swing.JTable jTable_mesVentas;
    private javax.swing.JTable jTable_muestras;
    private javax.swing.JTable jTable_ventas;
    private com.toedter.calendar.JYearChooser jYearChooser;
    private javax.swing.JTextField txt_Lucro;
    private javax.swing.JTextField txt_Lucro2;
    private javax.swing.JTextField txt_compras;
    private javax.swing.JTextField txt_compras2;
    private javax.swing.JTextField txt_delivery;
    private javax.swing.JTextField txt_muestras;
    private javax.swing.JTextField txt_ventas;
    private javax.swing.JTextField txt_ventas2;
    // End of variables declaration//GEN-END:variables

    public float sumaCompra() {
        int contar = jTable_mesVentas.getRowCount();
        float sumaCompra = 0;
        for (int i = 0; i < contar; i++) {

            sumaCompra = sumaCompra + Float.parseFloat(jTable_mesVentas.getValueAt(i, 3).toString());
        }
        return sumaCompra;
    }
    
    public float sumaMesCompra() {
        int contar = jTable_mesCompras.getRowCount();
        float sumaMesCompra = 0;
        for (int i = 0; i < contar; i++) {

            sumaMesCompra = sumaMesCompra + Float.parseFloat(jTable_mesCompras.getValueAt(i, 1).toString());
        }
        return sumaMesCompra;
    }
    
    public float totalCompra() {
        int contar = jTable_compras.getRowCount();
        float totalCompra = 0;
        for (int i = 0; i < contar; i++) {

            totalCompra = totalCompra + Float.parseFloat(jTable_compras.getValueAt(i, 4).toString());
        }
        return totalCompra;
    }
    public float totalVenta() {
        int contar = jTable_ventas.getRowCount();
        float totalVenta = 0;
        for (int i = 0; i < contar; i++) {

            totalVenta = totalVenta + Float.parseFloat(jTable_ventas.getValueAt(i, 6).toString());
        }
        return totalVenta;
    }

    public float sumaVenta() {
        int contar = jTable_mesVentas.getRowCount();
        float sumaVenta = 0;
        for (int i = 0; i < contar; i++) {

            sumaVenta = sumaVenta + Float.parseFloat(jTable_mesVentas.getValueAt(i, 4).toString());
        }
        return sumaVenta;
    }

    public float Delivery() {
        int contar = jTable_mesVentas.getRowCount();
        float Delivery = 0;
        for (int i = 0; i < contar; i++) {

            Delivery = Delivery + Float.parseFloat(jTable_mesVentas.getValueAt(i, 2).toString());
        }
        return Delivery;
    }
    
    public float totalDelivery() {
        int contar = jTable_ventas.getRowCount();
        float totalDelivery = 0;
        for (int i = 0; i < contar; i++) {

            totalDelivery = totalDelivery + Float.parseFloat(jTable_ventas.getValueAt(i, 4).toString());
        }
        return totalDelivery;
    }

    public float Muestras() {
        int contar = jTable_muestras.getRowCount();
        float Muestras = 0;
        for (int i = 0; i < contar; i++) {

            Muestras = Muestras + Float.parseFloat(jTable_muestras.getValueAt(i, 3).toString());
        }
        return Muestras;
    }

    public float Lucro() {

        float lucro = 0;

        int contarCompra = jTable_mesCompras.getRowCount();
        for (int i = 0; i < contarCompra; i++) {
        }

        lucro = sumaVenta() - sumaCompra() - Delivery() - sumaMesCompra();

        return lucro;
    }
    
    public float totalLucro() {

        float totalLucro = 0;

        int contarCompra = jTable_compras.getRowCount();
        float sumaFlete = 0;
        for (int i = 0; i < contarCompra; i++) {
            sumaFlete = sumaFlete + Float.parseFloat(jTable_compras.getValueAt(i, 5).toString());
        }

        totalLucro = totalVenta() - totalCompra() - sumaFlete - totalDelivery();

        return totalLucro;
    }

}
